from __future__ import annotations

import re
from pathlib import Path
from typing import Tuple

ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = ROOT / "VERSION"
VERSION_RE = re.compile(r"^v?(?P<version>\d+\.\d+\.\d+(?:-[0-9A-Za-z][0-9A-Za-z.-]*)?)$")


def normalize_tag_or_version(value: str) -> str:
    raw = str(value or "").strip()
    match = VERSION_RE.match(raw)
    if not match:
        raise ValueError(f"Invalid version/tag: {raw!r}")
    return match.group("version")


def read_version() -> str:
    if not VERSION_FILE.exists():
        return "1.0.0"
    return normalize_tag_or_version(VERSION_FILE.read_text(encoding="utf-8").strip())


def write_version(version: str) -> str:
    normalized = normalize_tag_or_version(version)
    VERSION_FILE.write_text(normalized + "\n", encoding="utf-8")
    return normalized


def windows_file_version_tuple(version: str) -> Tuple[int, int, int, int]:
    normalized = normalize_tag_or_version(version)
    core, _, prerelease = normalized.partition("-")
    major, minor, patch = [int(part) for part in core.split(".")]
    build = 0
    if prerelease:
        numeric = [int(part) for part in re.findall(r"\d+", prerelease)]
        if numeric:
            build = min(max(numeric[-1], 0), 65535)
    return major, minor, patch, build


def windows_file_version(version: str) -> str:
    return ".".join(str(part) for part in windows_file_version_tuple(version))


def pyinstaller_version_info_text(version: str) -> str:
    normalized = normalize_tag_or_version(version)
    major, minor, patch, build = windows_file_version_tuple(normalized)
    numeric = f"{major}.{minor}.{patch}.{build}"
    return f'''# UTF-8
# Generated by build_tools/write_version_info.py. Source version: {normalized}
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'BioAuth'),
         StringStruct('FileDescription', 'BioAuth Desktop'),
         StringStruct('FileVersion', '{normalized}'),
         StringStruct('InternalName', 'BioAuth'),
         StringStruct('OriginalFilename', 'BioAuth.exe'),
         StringStruct('ProductName', 'BioAuth Desktop'),
         StringStruct('ProductVersion', '{normalized}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''
